#  BRONZE (Dados Brutos)
Dados exatamente como chegam da fonte<br>
Sem transformações<br>
Serve como backup histórico<br>

## PROCESSAMENTO DOS DADOS

### IMPORTAÇÃO DAS BIBLIOTECAS

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
from datetime import datetime
import seaborn as sns
import numpy as np

### CRIAÇÃO DA ESTRUTURA DE PASTAS

In [2]:
os.makedirs('data/bronze', exist_ok=True)
os.makedirs('data/silver', exist_ok=True)
os.makedirs('data/gold', exist_ok=True)

### CARREGAMENTO DOS DADOS

In [3]:
df = pd.read_excel("dados_credito.xlsx")

print("Dimensão inicial do dataset:", df.shape)
df.info()
df.describe(include='all').T

Dimensão inicial do dataset: (10476, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10476 entries, 0 to 10475
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CODIGO_CLIENTE              10476 non-null  int64
 1   UF                          10476 non-null  object
 2   IDADE                       10476 non-null  int64
 3   ESCOLARIDADE                10476 non-null  object
 4   ESTADO_CIVIL                10476 non-null  object
 5   QT_FILHOS                   10476 non-null  int64
 6   CASA_PROPRIA                10476 non-null  object
 7   QT_IMOVEIS                  10476 non-null  int64
 8   VL_IMOVEIS                  10476 non-null  int64
 9   OUTRA_RENDA                 10476 non-null  object
 10  OUTRA_RENDA_VALOR           10476 non-null  int64
 11  TEMPO_ULTIMO_EMPREGO_MESES  10476 non-null  int64
 12  TRABALHANDO_ATUALMENTE      10476 non-null  object
 13  ULTIMO_SALARIO              10474 non-null  object
 14  QT_CARROS                   10476 non-null  int64
 15  VALOR_TABELA_CARROS         10476 non-null  int64
 16  SCORE                       10476 non-null  float64
dtypes: float64(1), int64(9), object(7)
memory usage: 1.4+ MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CODIGO_CLIENTE,10476.0,NaN,NaN,NaN,5238.5,3024.305044,1.0,2619.75,5238.5,7857.25,10476.0
UF,10476,5,RJ,2916,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IDADE,10476.0,NaN,NaN,NaN,41.054124,13.878162,19.0,28.0,42.0,53.0,65.0
ESCOLARIDADE,10476,3,Superior Completo,3672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ESTADO_CIVIL,10476,4,Casado,4716,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QT_FILHOS,10476.0,NaN,NaN,NaN,1.122566,1.113537,0.0,0.0,1.0,2.0,42.0
CASA_PROPRIA,10476,2,Não,5724,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QT_IMOVEIS,10476.0,NaN,NaN,NaN,0.847079,0.957374,0.0,0.0,1.0,1.0,3.0
VL_IMOVEIS,10476.0,NaN,NaN,NaN,238453.608247,265843.934416,0.0,0.0,185000.0,370000.0,900000.0
OUTRA_RENDA,10476,2,Não,8352,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OUTRA_RENDA_VALOR,10476.0,NaN,NaN,NaN,641.237113,1295.978195,0.0,0.0,0.0,0.0,4000.0
TEMPO_ULTIMO_EMPREGO_MESES,10476.0,NaN,NaN,NaN,43.070447,40.851521,8.0,14.0,22.0,75.0,150.0
TRABALHANDO_ATUALMENTE,10476,2,Sim,6336,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ULTIMO_SALARIO,10474.0,18.0,1800.0,846.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QT_CARROS,10476.0,NaN,NaN,NaN,0.936426,0.806635,0.0,0.0,1.0,2.0,2.0
VALOR_TABELA_CARROS,10476.0,NaN,NaN,NaN,40996.563574,47404.214062,0.0,0.0,35000.0,50000.0,180000.0
SCORE,10476.0,NaN,NaN,NaN,51.058706,27.30634,12.0,28.666667,45.166667,72.666667,98.0

## ANÁLISE DOS DADOS

### INSPEÇÃO INICIAL

In [4]:
df.info()
df.describe(include='all').T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10476 entries, 0 to 10475
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CODIGO_CLIENTE              10476 non-null  int64
 1   UF                          10476 non-null  object
 2   IDADE                       10476 non-null  int64
 3   ESCOLARIDADE                10476 non-null  object
 4   ESTADO_CIVIL                10476 non-null  object
 5   QT_FILHOS                   10476 non-null  int64
 6   CASA_PROPRIA                10476 non-null  object
 7   QT_IMOVEIS                  10476 non-null  int64
 8   VL_IMOVEIS                  10476 non-null  int64
 9   OUTRA_RENDA                 10476 non-null  object
 10  OUTRA_RENDA_VALOR           10476 non-null  int64
 11  TEMPO_ULTIMO_EMPREGO_MESES  10476 non-null  int64
 12  TRABALHANDO_ATUALMENTE      10476 non-null  object
 13  ULTIMO_SALARIO              10474 non-null  object
 14  QT_CARROS                   10476 non-null  int64
 15  VALOR_TABELA_CARROS         10476 non-null  int64
 16  SCORE                       10476 non-null  float64
dtypes: float64(1), int64(9), object(7)
memory usage: 1.4+ MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
CODIGO_CLIENTE,10476.0,NaN,NaN,NaN,5238.5,3024.305044,1.0,2619.75,5238.5,7857.25,10476.0
UF,10476,5,RJ,2916,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IDADE,10476.0,NaN,NaN,NaN,41.054124,13.878162,19.0,28.0,42.0,53.0,65.0
ESCOLARIDADE,10476,3,Superior Completo,3672,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ESTADO_CIVIL,10476,4,Casado,4716,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QT_FILHOS,10476.0,NaN,NaN,NaN,1.122566,1.113537,0.0,0.0,1.0,2.0,42.0
CASA_PROPRIA,10476,2,Não,5724,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QT_IMOVEIS,10476.0,NaN,NaN,NaN,0.847079,0.957374,0.0,0.0,1.0,1.0,3.0
VL_IMOVEIS,10476.0,NaN,NaN,NaN,238453.608247,265843.934416,0.0,0.0,185000.0,370000.0,900000.0
OUTRA_RENDA,10476,2,Não,8352,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OUTRA_RENDA_VALOR,10476.0,NaN,NaN,NaN,641.237113,1295.978195,0.0,0.0,0.0,0.0,4000.0
TEMPO_ULTIMO_EMPREGO_MESES,10476.0,NaN,NaN,NaN,43.070447,40.851521,8.0,14.0,22.0,75.0,150.0
TRABALHANDO_ATUALMENTE,10476,2,Sim,6336,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ULTIMO_SALARIO,10474.0,18.0,1800.0,846.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
QT_CARROS,10476.0,NaN,NaN,NaN,0.936426,0.806635,0.0,0.0,1.0,2.0,2.0
VALOR_TABELA_CARROS,10476.0,NaN,NaN,NaN,40996.563574,47404.214062,0.0,0.0,35000.0,50000.0,180000.0
SCORE,10476.0,NaN,NaN,NaN,51.058706,27.30634,12.0,28.666667,45.166667,72.666667,98.0

## SALVAR NA CAMADA BRONZE

### ADIÇÃO DA INFORMAÇÃO DE CARREGAMENTO DOS DADOS

In [5]:
df['DATA_UPLOAD'] = datetime.now()
df['ARQUIVO_FONTE'] = os.path.basename("dados_credito.xlsx")

### SALVAR DADOS NA CAMADA BRONZE EM ARQUIVO CSV

In [6]:
bronze_path = 'data/bronze/dados_brutos.csv'
df.to_csv(bronze_path, index=False)
print(f'>>> Bronze salvo em: {bronze_path}')
df.head()

>>> Bronze salvo em: data/bronze/dados_brutos.csv

,CODIGO_CLIENTE,UF,IDADE,ESCOLARIDADE,ESTADO_CIVIL,QT_FILHOS,CASA_PROPRIA,QT_IMOVEIS,VL_IMOVEIS,OUTRA_RENDA,OUTRA_RENDA_VALOR,TEMPO_ULTIMO_EMPREGO_MESES,TRABALHANDO_ATUALMENTE,ULTIMO_SALARIO,QT_CARROS,VALOR_TABELA_CARROS,SCORE,DATA_UPLOAD,ARQUIVO_FONTE
0,1,SP,19,Superior Cursando,Solteiro,0,Não,0,0,Não,0,8,Sim,1800,0,0,12.000000,2025-11-04 09:47:35.324676,dados_credito.xlsx
1,2,MG,23,Superior Completo,Solteiro,1,Não,0,0,Não,0,9,Não,4800,1,50000,18.000000,2025-11-04 09:47:35.324676,dados_credito.xlsx
2,3,SC,25,Segundo Grau Completo,Casado,0,Sim,1,220000,Não,0,18,Sim,2200,2,30000,23.000000,2025-11-04 09:47:35.324676,dados_credito.xlsx
3,4,PR,27,Superior Cursando,Casado,1,Sim,0,0,Não,0,22,Não,3900,0,0,28.666667,2025-11-04 09:47:35.324676,dados_credito.xlsx
4,5,RJ,28,Superior Completo,Divorciado,2,Não,1,370000,Não,0,30,Sim,NaN,1,35000,34.166667,2025-11-04 09:47:35.324676,dados_credito.xlsx